/**
 * Mock Data for Seeding Script
 * JavaScript version of the TypeScript mock data - synced with frontend
 */

// ===========================================
// Sample Video URLs and Thumbnails
// ===========================================
const SAMPLE_VIDEOS = {
  bigBuckBunny: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  elephantsDream: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
  forBiggerBlazes: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  forBiggerEscapes: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
  forBiggerFun: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
  forBiggerJoyrides: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
  forBiggerMeltdowns: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
  sintel: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
  subaru: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
  tearsOfSteel: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
  volkswagenGTI: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
  weAreGoingOnBullrun: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
  whatCarCanYouGetForAGrand: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
};

const SAMPLE_THUMBNAILS = {
  finance: "https://picsum.photos/seed/finance/400/225",
  tech: "https://picsum.photos/seed/tech/400/225",
  money: "https://picsum.photos/seed/money/400/225",
  business: "https://picsum.photos/seed/business/400/225",
  tips: "https://picsum.photos/seed/tips/400/225",
  savings: "https://picsum.photos/seed/savings/400/225",
  investment: "https://picsum.photos/seed/investment/400/225",
  tutorial: "https://picsum.photos/seed/tutorial/400/225",
  survey: "https://picsum.photos/seed/survey/400/225",
  earnings: "https://picsum.photos/seed/earnings/400/225",
  mobile: "https://picsum.photos/seed/mobile/400/225",
  rewards: "https://picsum.photos/seed/rewards/400/225",
};

// ===========================================
// Helper Functions
// ===========================================
const getFutureDate = (daysFromNow) => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  date.setHours(23, 59, 59, 0);
  return date.toISOString();
};

const getTodayDate = () => {
  return new Date().toISOString();
};

// ===========================================
// Mock Users
// ===========================================
export const mockUsers = [
  {
    id: "user_001",
    email: "john.doe@example.com",
    firstName: "John",
    lastName: "Doe",
    phone: "+256 700 123 456",
    points: 12500,
    avatar: "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png",
    role: "ADMIN",
    subscriptionStatus: "ACTIVE",
    surveysubscriptionStatus: "ACTIVE",
    currentSubscriptionId: "sub_001",
    privacySettings: { showEmail: false, showPhone: false },
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2026-01-04T00:00:00Z",
  },
  {
    id: "user_002",
    email: "sarah.johnson@example.com",
    firstName: "Sarah",
    lastName: "Johnson",
    phone: "+256 700 234 567",
    points: 8900,
    avatar: "https://randomuser.me/api/portraits/women/44.jpg",
    role: "USER",
    subscriptionStatus: "ACTIVE",
    surveysubscriptionStatus: "INACTIVE",
    currentSubscriptionId: "sub_002",
    privacySettings: null,
    createdAt: "2025-02-15T00:00:00Z",
    updatedAt: "2026-01-03T00:00:00Z",
  },
  {
    id: "user_003",
    email: "mike.chen@example.com",
    firstName: "Mike",
    lastName: "Chen",
    phone: "+256 700 345 678",
    points: 15200,
    avatar: "https://randomuser.me/api/portraits/men/32.jpg",
    role: "MODERATOR",
    subscriptionStatus: "INACTIVE",
    surveysubscriptionStatus: "ACTIVE",
    currentSubscriptionId: null,
    privacySettings: { showEmail: true, showPhone: false },
    createdAt: "2025-03-10T00:00:00Z",
    updatedAt: "2026-01-02T00:00:00Z",
  },
  {
    id: "user_004",
    email: "alice.smith@example.com",
    firstName: "Alice",
    lastName: "Smith",
    phone: "+256 700 456 789",
    points: 6750,
    avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    role: "USER",
    subscriptionStatus: "PENDING",
    surveysubscriptionStatus: "INACTIVE",
    currentSubscriptionId: null,
    privacySettings: null,
    createdAt: "2025-04-20T00:00:00Z",
    updatedAt: "2026-01-04T00:00:00Z",
  },
  {
    id: "user_admin",
    email: "admin@delipucash.com",
    firstName: "Admin",
    lastName: "User",
    phone: "+256 700 000 001",
    points: 100000,
    avatar: "https://ui-avatars.com/api/?name=Admin&background=6366f1&color=fff&bold=true",
    role: "ADMIN",
    subscriptionStatus: "ACTIVE",
    surveysubscriptionStatus: "ACTIVE",
    currentSubscriptionId: "sub_admin",
    privacySettings: { showEmail: false, showPhone: false },
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2026-01-28T00:00:00Z",
  },
];

// ===========================================
// Mock Videos
// ===========================================
export const mockVideos = [
  {
    id: "video_001",
    title: "How to Earn $100 Daily on Delipucash",
    description: "Complete guide to maximizing your earnings on the platform. Learn the secrets of top earners and how you can replicate their success.",
    videoUrl: SAMPLE_VIDEOS.forBiggerFun,
    thumbnail: SAMPLE_THUMBNAILS.earnings,
    userId: "user_002",
    likes: 892,
    views: 12450,
    duration: 60,
    isBookmarked: false,
    commentsCount: 45,
    createdAt: "2026-01-02T08:00:00Z",
    updatedAt: "2026-01-04T10:00:00Z",
  },
  {
    id: "video_002",
    title: "Live Q&A: Making Money Online",
    description: "Join us for tips and tricks on maximizing your online income. Our experts answer your burning questions about earning from home.",
    videoUrl: SAMPLE_VIDEOS.forBiggerJoyrides,
    thumbnail: SAMPLE_THUMBNAILS.money,
    userId: "user_003",
    likes: 456,
    views: 3240,
    duration: 15,
    isBookmarked: true,
    commentsCount: 128,
    createdAt: "2026-01-04T14:00:00Z",
    updatedAt: "2026-01-04T14:00:00Z",
  },
  {
    id: "video_003",
    title: "Survey Tips for Maximum Rewards",
    description: "How to qualify for high-paying surveys every time. These proven strategies will help you maximize your survey earnings.",
    videoUrl: SAMPLE_VIDEOS.forBiggerBlazes,
    thumbnail: SAMPLE_THUMBNAILS.survey,
    userId: "user_004",
    likes: 721,
    views: 8920,
    duration: 15,
    isBookmarked: false,
    commentsCount: 32,
    createdAt: "2026-01-03T16:30:00Z",
    updatedAt: "2026-01-03T16:30:00Z",
  },
  {
    id: "video_004",
    title: "Airtel Money Withdrawal Guide",
    description: "Step-by-step tutorial for withdrawing your earnings to Airtel Money. Quick, easy, and secure transactions explained.",
    videoUrl: SAMPLE_VIDEOS.forBiggerEscapes,
    thumbnail: SAMPLE_THUMBNAILS.mobile,
    userId: "user_002",
    likes: 1204,
    views: 15680,
    duration: 15,
    isBookmarked: true,
    commentsCount: 67,
    createdAt: "2026-01-01T12:00:00Z",
    updatedAt: "2026-01-01T12:00:00Z",
  },
  {
    id: "video_005",
    title: "How to Save Money in 2026",
    description: "Practical tips for saving money this year. Start building your financial future with these simple yet effective strategies.",
    videoUrl: SAMPLE_VIDEOS.forBiggerMeltdowns,
    thumbnail: SAMPLE_THUMBNAILS.savings,
    userId: "user_003",
    likes: 543,
    views: 1200,
    duration: 13,
    isBookmarked: false,
    commentsCount: 21,
    createdAt: "2025-12-28T10:00:00Z",
    updatedAt: "2025-12-28T10:00:00Z",
  },
  {
    id: "video_006",
    title: "Investment Tips for Beginners",
    description: "Start your investment journey with these essential tips. Learn how to grow your money wisely even with a small starting capital.",
    videoUrl: SAMPLE_VIDEOS.volkswagenGTI,
    thumbnail: SAMPLE_THUMBNAILS.investment,
    userId: "user_002",
    likes: 387,
    views: 850,
    duration: 160,
    isBookmarked: false,
    commentsCount: 15,
    createdAt: "2025-12-25T14:00:00Z",
    updatedAt: "2025-12-25T14:00:00Z",
  },
  {
    id: "video_007",
    title: "Complete Platform Tutorial",
    description: "A comprehensive walkthrough of all Delipucash features. From signing up to cashing out, we cover everything you need to know.",
    videoUrl: SAMPLE_VIDEOS.weAreGoingOnBullrun,
    thumbnail: SAMPLE_THUMBNAILS.tutorial,
    userId: "user_003",
    likes: 1567,
    views: 25000,
    duration: 48,
    isBookmarked: true,
    commentsCount: 89,
    createdAt: "2026-01-05T09:00:00Z",
    updatedAt: "2026-01-05T09:00:00Z",
  },
  {
    id: "video_008",
    title: "Top 10 Earning Strategies",
    description: "Discover the top 10 strategies used by our highest earners. These methods have been proven to generate consistent income.",
    videoUrl: SAMPLE_VIDEOS.whatCarCanYouGetForAGrand,
    thumbnail: SAMPLE_THUMBNAILS.business,
    userId: "user_004",
    likes: 2340,
    views: 45000,
    duration: 165,
    isBookmarked: false,
    commentsCount: 156,
    createdAt: "2026-01-06T11:30:00Z",
    updatedAt: "2026-01-06T11:30:00Z",
  },
  {
    id: "video_009",
    title: "Understanding Instant Rewards",
    description: "Everything you need to know about our instant reward system. Answer questions correctly and get paid instantly to your mobile money.",
    videoUrl: SAMPLE_VIDEOS.subaru,
    thumbnail: SAMPLE_THUMBNAILS.rewards,
    userId: "user_002",
    likes: 678,
    views: 8900,
    duration: 59,
    isBookmarked: false,
    commentsCount: 42,
    createdAt: "2026-01-07T15:00:00Z",
    updatedAt: "2026-01-07T15:00:00Z",
  },
  {
    id: "video_010",
    title: "Mobile App Features Deep Dive",
    description: "Explore all the features of our mobile app. Tips and tricks to navigate the app like a pro and maximize your experience.",
    videoUrl: SAMPLE_VIDEOS.forBiggerFun,
    thumbnail: SAMPLE_THUMBNAILS.tech,
    userId: "user_003",
    likes: 445,
    views: 6200,
    duration: 60,
    isBookmarked: true,
    commentsCount: 28,
    createdAt: "2026-01-08T10:00:00Z",
    updatedAt: "2026-01-08T10:00:00Z",
  },
];

// ===========================================
// Mock Comments
// ===========================================
export const mockComments = [
  {
    id: "comment_001",
    text: "This video really helped me understand how to earn more!",
    mediaUrls: [],
    userId: "user_001",
    videoId: "video_001",
    createdAt: "2026-01-02T10:30:00Z",
  },
  {
    id: "comment_002",
    text: "Great tips! Thanks for sharing 🙏",
    mediaUrls: [],
    userId: "user_003",
    videoId: "video_001",
    createdAt: "2026-01-02T11:45:00Z",
  },
  {
    id: "comment_003",
    text: "Can you make a video about crypto rewards?",
    mediaUrls: [],
    userId: "user_004",
    videoId: "video_002",
    createdAt: "2026-01-04T14:30:00Z",
  },
];

// ===========================================
// Mock Surveys
// ===========================================
export const mockSurveys = [
  {
    id: "survey_001",
    title: "Customer Satisfaction Survey",
    description: "Help us improve our services by sharing your feedback",
    userId: "user_002",
    startDate: "2026-02-01T00:00:00Z",
    endDate: "2026-04-30T23:59:59Z",
    createdAt: "2025-12-28T00:00:00Z",
    updatedAt: "2026-01-04T00:00:00Z",
    totalResponses: 234,
    maxResponses: 500,
    rewardAmount: 2000,
    status: "running",
  },
  {
    id: "survey_002",
    title: "Product Feedback Survey",
    description: "Share your thoughts on our new features and help us build better products",
    userId: "user_003",
    startDate: "2026-02-05T00:00:00Z",
    endDate: "2026-04-30T23:59:59Z",
    createdAt: "2025-12-30T00:00:00Z",
    updatedAt: "2026-01-03T00:00:00Z",
    totalResponses: 89,
    maxResponses: 200,
    rewardAmount: 2000,
    status: "running",
  },
  {
    id: "survey_003",
    title: "User Experience Study",
    description: "Tell us about your app experience and how we can improve it",
    userId: "user_002",
    startDate: "2026-02-01T00:00:00Z",
    endDate: "2026-04-30T23:59:59Z",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
    totalResponses: 45,
    maxResponses: 300,
    rewardAmount: 2000,
    status: "running",
  },
  {
    id: "survey_004",
    title: "Mobile App Usability Survey",
    description: "Help us improve the mobile experience with your valuable feedback",
    userId: "user_004",
    startDate: "2026-02-01T00:00:00Z",
    endDate: "2026-04-30T23:59:59Z",
    createdAt: "2026-01-03T00:00:00Z",
    updatedAt: "2026-01-03T00:00:00Z",
    totalResponses: 67,
    maxResponses: 150,
    rewardAmount: 2000,
    status: "running",
  },
  {
    id: "survey_005",
    title: "Digital Payment Habits Survey",
    description: "Share your mobile money and digital payment preferences",
    userId: "user_003",
    startDate: "2026-01-20T00:00:00Z",
    endDate: "2026-04-30T23:59:59Z",
    createdAt: "2026-01-18T00:00:00Z",
    updatedAt: "2026-01-18T00:00:00Z",
    totalResponses: 112,
    maxResponses: 400,
    rewardAmount: 2000,
    status: "running",
  },
  // Running survey #6
  {
    id: "survey_006",
    title: "Content Quality Assessment",
    description: "Rate the quality of videos, questions, and educational content available on our platform",
    userId: "user_002",
    startDate: "2026-01-25T00:00:00Z",
    endDate: "2026-04-30T23:59:59Z",
    createdAt: "2026-01-22T00:00:00Z",
    updatedAt: "2026-01-22T00:00:00Z",
    totalResponses: 156,
    maxResponses: 350,
    rewardAmount: 2000,
    status: "running",
  },
  // Upcoming / Scheduled surveys
  {
    id: "survey_007",
    title: "Financial Literacy Survey",
    description: "Help us understand financial education needs in your community to create better learning content",
    userId: "user_003",
    startDate: "2026-03-01T00:00:00Z",
    endDate: "2026-05-30T23:59:59Z",
    createdAt: "2026-02-05T00:00:00Z",
    updatedAt: "2026-02-05T00:00:00Z",
    totalResponses: 0,
    maxResponses: 600,
    rewardAmount: 2000,
    status: "scheduled",
  },
  {
    id: "survey_008",
    title: "Community Engagement Survey",
    description: "Share your ideas on how we can build a stronger, more connected user community",
    userId: "user_004",
    startDate: "2026-03-15T00:00:00Z",
    endDate: "2026-06-15T23:59:59Z",
    createdAt: "2026-02-06T00:00:00Z",
    updatedAt: "2026-02-06T00:00:00Z",
    totalResponses: 0,
    maxResponses: 400,
    rewardAmount: 2000,
    status: "scheduled",
  },
  {
    id: "survey_009",
    title: "Platform Feature Wishlist",
    description: "Vote on and suggest new features you'd like to see in our next major update",
    userId: "user_002",
    startDate: "2026-04-01T00:00:00Z",
    endDate: "2026-06-30T23:59:59Z",
    createdAt: "2026-02-07T00:00:00Z",
    updatedAt: "2026-02-07T00:00:00Z",
    totalResponses: 0,
    maxResponses: 500,
    rewardAmount: 2000,
    status: "scheduled",
  },
  {
    id: "survey_010",
    title: "Advertising Preferences Survey",
    description: "Tell us about your ad preferences so we can show you more relevant and less intrusive ads",
    userId: "user_003",
    startDate: "2026-03-20T00:00:00Z",
    endDate: "2026-05-20T23:59:59Z",
    createdAt: "2026-02-08T00:00:00Z",
    updatedAt: "2026-02-08T00:00:00Z",
    totalResponses: 0,
    maxResponses: 350,
    rewardAmount: 2000,
    status: "scheduled",
  },
  // Completed surveys
  {
    id: "survey_011",
    title: "Beta Launch Feedback Survey",
    description: "Thank you for providing feedback during our beta launch phase! Your input shaped our product",
    userId: "user_002",
    startDate: "2025-10-01T00:00:00Z",
    endDate: "2025-12-31T23:59:59Z",
    createdAt: "2025-09-28T00:00:00Z",
    updatedAt: "2025-12-31T00:00:00Z",
    totalResponses: 500,
    maxResponses: 500,
    rewardAmount: 2000,
    status: "completed",
  },
  {
    id: "survey_012",
    title: "Holiday Season Shopping Survey",
    description: "This survey helped us understand holiday spending habits and shopping preferences",
    userId: "user_003",
    startDate: "2025-11-15T00:00:00Z",
    endDate: "2026-01-15T23:59:59Z",
    createdAt: "2025-11-10T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
    totalResponses: 378,
    maxResponses: 400,
    rewardAmount: 2000,
    status: "completed",
  },
  {
    id: "survey_013",
    title: "New Year Resolutions Survey",
    description: "We gathered insights about user goals and resolutions to improve our services in 2026",
    userId: "user_004",
    startDate: "2025-12-20T00:00:00Z",
    endDate: "2026-01-31T23:59:59Z",
    createdAt: "2025-12-18T00:00:00Z",
    updatedAt: "2026-01-31T00:00:00Z",
    totalResponses: 289,
    maxResponses: 300,
    rewardAmount: 2000,
    status: "completed",
  },
  {
    id: "survey_014",
    title: "App Onboarding Experience Survey",
    description: "User feedback on the sign-up and onboarding flow helped us simplify the process",
    userId: "user_002",
    startDate: "2025-11-01T00:00:00Z",
    endDate: "2026-01-20T23:59:59Z",
    createdAt: "2025-10-28T00:00:00Z",
    updatedAt: "2026-01-20T00:00:00Z",
    totalResponses: 450,
    maxResponses: 450,
    rewardAmount: 2000,
    status: "completed",
  },
];

// ===========================================
// Mock Survey Questions
// ===========================================
export const mockSurveyQuestions = [
  {
    id: "sq_001",
    text: "How satisfied are you with our platform?",
    type: "rating",
    options: JSON.stringify({ min: 1, max: 5, labels: ["Very Unsatisfied", "Unsatisfied", "Neutral", "Satisfied", "Very Satisfied"] }),
    placeholder: null,
    minValue: 1,
    maxValue: 5,
    userId: "user_002",
    surveyId: "survey_001",
    createdAt: "2025-12-28T00:00:00Z",
    updatedAt: "2025-12-28T00:00:00Z",
  },
  {
    id: "sq_002",
    text: "Which features do you use most?",
    type: "checkbox",
    options: JSON.stringify(["Questions & Answers", "Surveys", "Videos", "Live Streaming", "Rewards"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_002",
    surveyId: "survey_001",
    createdAt: "2025-12-28T00:00:00Z",
    updatedAt: "2025-12-28T00:00:00Z",
  },
  {
    id: "sq_003",
    text: "How did you hear about us?",
    type: "radio",
    options: JSON.stringify(["Social Media", "Friend Referral", "Search Engine", "Advertisement", "Other"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_002",
    surveyId: "survey_001",
    createdAt: "2025-12-28T00:00:00Z",
    updatedAt: "2025-12-28T00:00:00Z",
  },
  {
    id: "sq_004",
    text: "What improvements would you like to see?",
    type: "text",
    options: JSON.stringify({ multiline: true, placeholder: "Share your suggestions..." }),
    placeholder: "Share your suggestions...",
    minValue: null,
    maxValue: null,
    userId: "user_002",
    surveyId: "survey_001",
    createdAt: "2025-12-28T00:00:00Z",
    updatedAt: "2025-12-28T00:00:00Z",
  },
  // Survey 002 questions
  {
    id: "sq_005",
    text: "How would you rate the overall quality of our products?",
    type: "rating",
    options: JSON.stringify({ min: 1, max: 5, labels: ["Poor", "Fair", "Good", "Very Good", "Excellent"] }),
    placeholder: null,
    minValue: 1,
    maxValue: 5,
    userId: "user_003",
    surveyId: "survey_002",
    createdAt: "2025-12-30T00:00:00Z",
    updatedAt: "2025-12-30T00:00:00Z",
  },
  {
    id: "sq_006",
    text: "Which product features are most important to you?",
    type: "checkbox",
    options: JSON.stringify(["Ease of use", "Speed & Performance", "Security", "Customer Support", "Pricing"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_003",
    surveyId: "survey_002",
    createdAt: "2025-12-30T00:00:00Z",
    updatedAt: "2025-12-30T00:00:00Z",
  },
  {
    id: "sq_007",
    text: "How likely are you to recommend our product to a friend?",
    type: "radio",
    options: JSON.stringify(["Very Likely", "Likely", "Neutral", "Unlikely", "Very Unlikely"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_003",
    surveyId: "survey_002",
    createdAt: "2025-12-30T00:00:00Z",
    updatedAt: "2025-12-30T00:00:00Z",
  },
  {
    id: "sq_008",
    text: "What new features would you like us to add?",
    type: "text",
    options: JSON.stringify({ multiline: true, placeholder: "Tell us what you'd like..." }),
    placeholder: "Tell us what you'd like...",
    minValue: null,
    maxValue: null,
    userId: "user_003",
    surveyId: "survey_002",
    createdAt: "2025-12-30T00:00:00Z",
    updatedAt: "2025-12-30T00:00:00Z",
  },
  // Survey 003 questions
  {
    id: "sq_009",
    text: "How easy is it to navigate the app?",
    type: "rating",
    options: JSON.stringify({ min: 1, max: 5, labels: ["Very Difficult", "Difficult", "Neutral", "Easy", "Very Easy"] }),
    placeholder: null,
    minValue: 1,
    maxValue: 5,
    userId: "user_002",
    surveyId: "survey_003",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "sq_010",
    text: "Which sections of the app do you visit most?",
    type: "checkbox",
    options: JSON.stringify(["Home", "Surveys", "Questions", "Videos", "Wallet", "Profile"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_002",
    surveyId: "survey_003",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "sq_011",
    text: "How would you describe the app's loading speed?",
    type: "radio",
    options: JSON.stringify(["Very Fast", "Fast", "Average", "Slow", "Very Slow"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_002",
    surveyId: "survey_003",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  {
    id: "sq_012",
    text: "What aspect of the user experience needs the most improvement?",
    type: "text",
    options: JSON.stringify({ multiline: true, placeholder: "Share your experience..." }),
    placeholder: "Share your experience...",
    minValue: null,
    maxValue: null,
    userId: "user_002",
    surveyId: "survey_003",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-01-01T00:00:00Z",
  },
  // Survey 004 questions
  {
    id: "sq_013",
    text: "How often do you use our mobile app?",
    type: "radio",
    options: JSON.stringify(["Daily", "Several times a week", "Once a week", "A few times a month", "Rarely"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_004",
    surveyId: "survey_004",
    createdAt: "2026-01-03T00:00:00Z",
    updatedAt: "2026-01-03T00:00:00Z",
  },
  {
    id: "sq_014",
    text: "Which device do you primarily use?",
    type: "radio",
    options: JSON.stringify(["Android Phone", "iPhone", "Android Tablet", "iPad", "Other"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_004",
    surveyId: "survey_004",
    createdAt: "2026-01-03T00:00:00Z",
    updatedAt: "2026-01-03T00:00:00Z",
  },
  {
    id: "sq_015",
    text: "Rate your overall satisfaction with the mobile app",
    type: "rating",
    options: JSON.stringify({ min: 1, max: 5, labels: ["Very Unsatisfied", "Unsatisfied", "Neutral", "Satisfied", "Very Satisfied"] }),
    placeholder: null,
    minValue: 1,
    maxValue: 5,
    userId: "user_004",
    surveyId: "survey_004",
    createdAt: "2026-01-03T00:00:00Z",
    updatedAt: "2026-01-03T00:00:00Z",
  },
  {
    id: "sq_016",
    text: "Any additional feedback about the mobile experience?",
    type: "text",
    options: JSON.stringify({ multiline: true, placeholder: "Your feedback..." }),
    placeholder: "Your feedback...",
    minValue: null,
    maxValue: null,
    userId: "user_004",
    surveyId: "survey_004",
    createdAt: "2026-01-03T00:00:00Z",
    updatedAt: "2026-01-03T00:00:00Z",
  },
  // Survey 005 questions
  {
    id: "sq_017",
    text: "Which mobile money service do you use most?",
    type: "radio",
    options: JSON.stringify(["MTN Mobile Money", "Airtel Money", "Both equally", "Neither", "Other"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_003",
    surveyId: "survey_005",
    createdAt: "2026-01-18T00:00:00Z",
    updatedAt: "2026-01-18T00:00:00Z",
  },
  {
    id: "sq_018",
    text: "What do you mostly use mobile money for?",
    type: "checkbox",
    options: JSON.stringify(["Sending money", "Receiving money", "Paying bills", "Shopping online", "Savings", "Withdrawals"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_003",
    surveyId: "survey_005",
    createdAt: "2026-01-18T00:00:00Z",
    updatedAt: "2026-01-18T00:00:00Z",
  },
  {
    id: "sq_019",
    text: "How secure do you feel using digital payments?",
    type: "rating",
    options: JSON.stringify({ min: 1, max: 5, labels: ["Not Secure", "Slightly Secure", "Neutral", "Secure", "Very Secure"] }),
    placeholder: null,
    minValue: 1,
    maxValue: 5,
    userId: "user_003",
    surveyId: "survey_005",
    createdAt: "2026-01-18T00:00:00Z",
    updatedAt: "2026-01-18T00:00:00Z",
  },
  {
    id: "sq_020",
    text: "What would make you use digital payments more?",
    type: "text",
    options: JSON.stringify({ multiline: true, placeholder: "Share your thoughts..." }),
    placeholder: "Share your thoughts...",
    minValue: null,
    maxValue: null,
    userId: "user_003",
    surveyId: "survey_005",
    createdAt: "2026-01-18T00:00:00Z",
    updatedAt: "2026-01-18T00:00:00Z",
  },
  // Survey 006 questions (Running — Content Quality)
  {
    id: "sq_021",
    text: "How would you rate the overall quality of our content?",
    type: "rating",
    options: JSON.stringify({ min: 1, max: 5, labels: ["Very Poor", "Poor", "Average", "Good", "Excellent"] }),
    placeholder: null,
    minValue: 1,
    maxValue: 5,
    userId: "user_002",
    surveyId: "survey_006",
    createdAt: "2026-01-22T00:00:00Z",
    updatedAt: "2026-01-22T00:00:00Z",
  },
  {
    id: "sq_022",
    text: "Which content types do you enjoy most?",
    type: "checkbox",
    options: JSON.stringify(["Short Videos", "Educational Quizzes", "Polls & Surveys", "Live Streams", "Written Articles"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_002",
    surveyId: "survey_006",
    createdAt: "2026-01-22T00:00:00Z",
    updatedAt: "2026-01-22T00:00:00Z",
  },
  {
    id: "sq_023",
    text: "What topics would you like to see more content about?",
    type: "text",
    options: JSON.stringify({ multiline: true, placeholder: "Suggest new content topics..." }),
    placeholder: "Suggest new content topics...",
    minValue: null,
    maxValue: null,
    userId: "user_002",
    surveyId: "survey_006",
    createdAt: "2026-01-22T00:00:00Z",
    updatedAt: "2026-01-22T00:00:00Z",
  },
  // Survey 007 questions (Upcoming — Financial Literacy)
  {
    id: "sq_024",
    text: "How would you rate your understanding of personal finance?",
    type: "rating",
    options: JSON.stringify({ min: 1, max: 5, labels: ["Very Low", "Low", "Average", "Good", "Expert"] }),
    placeholder: null,
    minValue: 1,
    maxValue: 5,
    userId: "user_003",
    surveyId: "survey_007",
    createdAt: "2026-02-05T00:00:00Z",
    updatedAt: "2026-02-05T00:00:00Z",
  },
  {
    id: "sq_025",
    text: "Which financial topics interest you?",
    type: "checkbox",
    options: JSON.stringify(["Budgeting", "Saving & Investing", "Mobile Money Tips", "Loans & Credit", "Insurance", "Taxes"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_003",
    surveyId: "survey_007",
    createdAt: "2026-02-05T00:00:00Z",
    updatedAt: "2026-02-05T00:00:00Z",
  },
  {
    id: "sq_026",
    text: "How do you prefer to learn about finances?",
    type: "radio",
    options: JSON.stringify(["Short Videos", "Written Guides", "Interactive Quizzes", "Webinars", "One-on-one Coaching"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_003",
    surveyId: "survey_007",
    createdAt: "2026-02-05T00:00:00Z",
    updatedAt: "2026-02-05T00:00:00Z",
  },
  {
    id: "sq_027",
    text: "What is your biggest financial challenge right now?",
    type: "text",
    options: JSON.stringify({ multiline: true, placeholder: "Tell us about your challenge..." }),
    placeholder: "Tell us about your challenge...",
    minValue: null,
    maxValue: null,
    userId: "user_003",
    surveyId: "survey_007",
    createdAt: "2026-02-05T00:00:00Z",
    updatedAt: "2026-02-05T00:00:00Z",
  },
  // Survey 008 questions (Upcoming — Community Engagement)
  {
    id: "sq_028",
    text: "How connected do you feel to the DelipuCash community?",
    type: "rating",
    options: JSON.stringify({ min: 1, max: 5, labels: ["Not at All", "Slightly", "Moderately", "Very", "Extremely"] }),
    placeholder: null,
    minValue: 1,
    maxValue: 5,
    userId: "user_004",
    surveyId: "survey_008",
    createdAt: "2026-02-06T00:00:00Z",
    updatedAt: "2026-02-06T00:00:00Z",
  },
  {
    id: "sq_029",
    text: "Which community features would you like to see?",
    type: "checkbox",
    options: JSON.stringify(["Discussion Forums", "User Groups", "Community Challenges", "Leaderboards", "Mentorship Programs"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_004",
    surveyId: "survey_008",
    createdAt: "2026-02-06T00:00:00Z",
    updatedAt: "2026-02-06T00:00:00Z",
  },
  {
    id: "sq_030",
    text: "How often would you participate in community events?",
    type: "radio",
    options: JSON.stringify(["Daily", "Weekly", "Monthly", "Occasionally", "Never"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_004",
    surveyId: "survey_008",
    createdAt: "2026-02-06T00:00:00Z",
    updatedAt: "2026-02-06T00:00:00Z",
  },
  // Survey 009 questions (Upcoming — Feature Wishlist)
  {
    id: "sq_031",
    text: "How would you rate the current set of app features?",
    type: "rating",
    options: JSON.stringify({ min: 1, max: 5, labels: ["Very Lacking", "Lacking", "Adequate", "Good", "Excellent"] }),
    placeholder: null,
    minValue: 1,
    maxValue: 5,
    userId: "user_002",
    surveyId: "survey_009",
    createdAt: "2026-02-07T00:00:00Z",
    updatedAt: "2026-02-07T00:00:00Z",
  },
  {
    id: "sq_032",
    text: "Which upcoming features excite you most?",
    type: "checkbox",
    options: JSON.stringify(["Dark Mode", "Offline Mode", "Voice Surveys", "Group Challenges", "Referral Bonuses", "In-app Messaging"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_002",
    surveyId: "survey_009",
    createdAt: "2026-02-07T00:00:00Z",
    updatedAt: "2026-02-07T00:00:00Z",
  },
  {
    id: "sq_033",
    text: "Describe a feature you wish we had.",
    type: "text",
    options: JSON.stringify({ multiline: true, placeholder: "Your feature idea..." }),
    placeholder: "Your feature idea...",
    minValue: null,
    maxValue: null,
    userId: "user_002",
    surveyId: "survey_009",
    createdAt: "2026-02-07T00:00:00Z",
    updatedAt: "2026-02-07T00:00:00Z",
  },
  // Survey 010 questions (Upcoming — Advertising Preferences)
  {
    id: "sq_034",
    text: "How do you feel about seeing ads in the app?",
    type: "rating",
    options: JSON.stringify({ min: 1, max: 5, labels: ["Strongly Dislike", "Dislike", "Neutral", "Accept", "Don't Mind"] }),
    placeholder: null,
    minValue: 1,
    maxValue: 5,
    userId: "user_003",
    surveyId: "survey_010",
    createdAt: "2026-02-08T00:00:00Z",
    updatedAt: "2026-02-08T00:00:00Z",
  },
  {
    id: "sq_035",
    text: "Which ad formats are least disruptive to you?",
    type: "checkbox",
    options: JSON.stringify(["Banner Ads", "Rewarded Video Ads", "Native Ads in Feed", "Interstitial Ads", "Sponsored Content"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_003",
    surveyId: "survey_010",
    createdAt: "2026-02-08T00:00:00Z",
    updatedAt: "2026-02-08T00:00:00Z",
  },
  {
    id: "sq_036",
    text: "Would you watch a video ad in exchange for extra rewards?",
    type: "radio",
    options: JSON.stringify(["Yes, always", "Sometimes", "Rarely", "Never"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_003",
    surveyId: "survey_010",
    createdAt: "2026-02-08T00:00:00Z",
    updatedAt: "2026-02-08T00:00:00Z",
  },
  // Survey 011 questions (Completed — Beta Launch Feedback)
  {
    id: "sq_037",
    text: "Overall, how was your beta experience?",
    type: "rating",
    options: JSON.stringify({ min: 1, max: 5, labels: ["Terrible", "Poor", "Okay", "Good", "Amazing"] }),
    placeholder: null,
    minValue: 1,
    maxValue: 5,
    userId: "user_002",
    surveyId: "survey_011",
    createdAt: "2025-09-28T00:00:00Z",
    updatedAt: "2025-09-28T00:00:00Z",
  },
  {
    id: "sq_038",
    text: "Which beta features worked well?",
    type: "checkbox",
    options: JSON.stringify(["Account Creation", "Survey Completion", "Reward Withdrawal", "Video Watching", "Push Notifications"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_002",
    surveyId: "survey_011",
    createdAt: "2025-09-28T00:00:00Z",
    updatedAt: "2025-09-28T00:00:00Z",
  },
  {
    id: "sq_039",
    text: "Did you encounter any major bugs?",
    type: "radio",
    options: JSON.stringify(["No bugs at all", "Minor bugs only", "Some significant bugs", "Many bugs", "App was unusable"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_002",
    surveyId: "survey_011",
    createdAt: "2025-09-28T00:00:00Z",
    updatedAt: "2025-09-28T00:00:00Z",
  },
  // Survey 012 questions (Completed — Holiday Shopping)
  {
    id: "sq_040",
    text: "How much did you spend during the holiday season?",
    type: "radio",
    options: JSON.stringify(["Less than UGX 50,000", "UGX 50,000 – 200,000", "UGX 200,000 – 500,000", "UGX 500,000 – 1,000,000", "Over UGX 1,000,000"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_003",
    surveyId: "survey_012",
    createdAt: "2025-11-10T00:00:00Z",
    updatedAt: "2025-11-10T00:00:00Z",
  },
  {
    id: "sq_041",
    text: "What did you shop for?",
    type: "checkbox",
    options: JSON.stringify(["Clothing & Fashion", "Electronics", "Food & Groceries", "Gifts for Others", "Travel & Entertainment", "Home & Decor"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_003",
    surveyId: "survey_012",
    createdAt: "2025-11-10T00:00:00Z",
    updatedAt: "2025-11-10T00:00:00Z",
  },
  {
    id: "sq_042",
    text: "Rate your holiday shopping experience overall.",
    type: "rating",
    options: JSON.stringify({ min: 1, max: 5, labels: ["Very Stressful", "Stressful", "Neutral", "Enjoyable", "Very Enjoyable"] }),
    placeholder: null,
    minValue: 1,
    maxValue: 5,
    userId: "user_003",
    surveyId: "survey_012",
    createdAt: "2025-11-10T00:00:00Z",
    updatedAt: "2025-11-10T00:00:00Z",
  },
  // Survey 013 questions (Completed — New Year Resolutions)
  {
    id: "sq_043",
    text: "Did you set financial goals for 2026?",
    type: "radio",
    options: JSON.stringify(["Yes, detailed goals", "Yes, general goals", "Thinking about it", "No"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_004",
    surveyId: "survey_013",
    createdAt: "2025-12-18T00:00:00Z",
    updatedAt: "2025-12-18T00:00:00Z",
  },
  {
    id: "sq_044",
    text: "Which areas are you focusing on in 2026?",
    type: "checkbox",
    options: JSON.stringify(["Saving More Money", "Reducing Debt", "Investing", "Starting a Business", "Learning New Skills", "Health & Fitness"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_004",
    surveyId: "survey_013",
    createdAt: "2025-12-18T00:00:00Z",
    updatedAt: "2025-12-18T00:00:00Z",
  },
  {
    id: "sq_045",
    text: "How confident are you about achieving your goals?",
    type: "rating",
    options: JSON.stringify({ min: 1, max: 5, labels: ["Not Confident", "Slightly", "Moderately", "Confident", "Very Confident"] }),
    placeholder: null,
    minValue: 1,
    maxValue: 5,
    userId: "user_004",
    surveyId: "survey_013",
    createdAt: "2025-12-18T00:00:00Z",
    updatedAt: "2025-12-18T00:00:00Z",
  },
  // Survey 014 questions (Completed — Onboarding Experience)
  {
    id: "sq_046",
    text: "How easy was the sign-up process?",
    type: "rating",
    options: JSON.stringify({ min: 1, max: 5, labels: ["Very Difficult", "Difficult", "Neutral", "Easy", "Very Easy"] }),
    placeholder: null,
    minValue: 1,
    maxValue: 5,
    userId: "user_002",
    surveyId: "survey_014",
    createdAt: "2025-10-28T00:00:00Z",
    updatedAt: "2025-10-28T00:00:00Z",
  },
  {
    id: "sq_047",
    text: "Which sign-up method did you use?",
    type: "radio",
    options: JSON.stringify(["Email", "Phone Number", "Google Account", "Apple ID", "Facebook"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_002",
    surveyId: "survey_014",
    createdAt: "2025-10-28T00:00:00Z",
    updatedAt: "2025-10-28T00:00:00Z",
  },
  {
    id: "sq_048",
    text: "What parts of onboarding were most helpful?",
    type: "checkbox",
    options: JSON.stringify(["Welcome Tutorial", "Feature Walkthrough", "First Reward Bonus", "Profile Setup Guide", "FAQ Section"]),
    placeholder: null,
    minValue: null,
    maxValue: null,
    userId: "user_002",
    surveyId: "survey_014",
    createdAt: "2025-10-28T00:00:00Z",
    updatedAt: "2025-10-28T00:00:00Z",
  },
];

// ===========================================
// Mock Ads
// ===========================================
// ===========================================
// High-quality ad image URLs (Unsplash - free to use, seeded for consistency)
// ===========================================
const AD_IMAGES = {
  finance: "https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=800&h=400&fit=crop",
  banking: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&h=400&fit=crop",
  crypto: "https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=800&h=400&fit=crop",
  smartphone: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=400&fit=crop",
  laptop: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=400&fit=crop",
  fitness: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=400&fit=crop",
  food: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=400&fit=crop",
  travel: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&h=400&fit=crop",
  education: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=400&fit=crop",
  fashion: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&h=400&fit=crop",
  music: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&h=400&fit=crop",
  gaming: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=800&h=400&fit=crop",
  coffee: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&h=400&fit=crop",
  business: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&h=400&fit=crop",
  coding: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&h=400&fit=crop",
  sneakers: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=400&fit=crop",
  hotel: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=400&fit=crop",
  yoga: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=400&fit=crop",
  car: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&h=400&fit=crop",
  home: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=400&fit=crop",
};

const AD_VIDEOS = {
  forBiggerBlazes: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  forBiggerFun: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
  forBiggerEscapes: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
  forBiggerJoyrides: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
};

/**
 * Mock Ads — comprehensive seed data covering every placement & type.
 *
 * Placements (7 frontend):  home, feed, survey, video, question, profile, explore
 * Types (4 valid backend):  featured, banner, regular, compact
 *
 * Each placement has at least 2 ads (one featured/banner + one regular/compact)
 * so the UI always has content to display. Status is "approved" & isActive: true
 * with future endDates so they are returned by the GET /api/ads/all endpoint.
 */
export const mockAds = [
  // =========================================================================
  // PLACEMENT: home — premium hero slot on the home/dashboard screen
  // =========================================================================
  {
    id: "ad_001",
    title: "Premium Subscription — 50% Off!",
    headline: "Unlock Premium Features Today",
    description: "Upgrade to premium and unlock all features at half price. Ad-free experience, priority support, and exclusive rewards.",
    imageUrl: AD_IMAGES.finance,
    videoUrl: AD_VIDEOS.forBiggerBlazes,
    thumbnailUrl: AD_IMAGES.finance,
    type: "featured",
    placement: "home",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_002",
    priority: 10,
    frequency: 5,
    targetUrl: "https://example.com/premium",
    callToAction: "get_offer",
    pricingModel: "cpm",
    totalBudget: 10000,
    bidAmount: 2.50,
    dailyBudgetLimit: 400,
    targetAgeRanges: ["18-24", "25-34"],
    targetGender: "all",
    targetLocations: ["Uganda", "Kenya", "Tanzania"],
    targetInterests: ["technology", "finance", "earning"],
    enableRetargeting: true,
    status: "approved",
  },
  {
    id: "ad_002",
    title: "Mobile Money Made Easy",
    headline: "Send & Receive Instantly",
    description: "Transfer money to anyone in Uganda instantly. Zero fees on your first 10 transactions. Trusted by 2M+ users.",
    imageUrl: AD_IMAGES.smartphone,
    videoUrl: null,
    thumbnailUrl: AD_IMAGES.smartphone,
    type: "banner",
    placement: "home",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_003",
    priority: 8,
    frequency: 4,
    targetUrl: "https://example.com/mobile-money",
    callToAction: "sign_up",
    pricingModel: "cpc",
    totalBudget: 5000,
    bidAmount: 1.20,
    dailyBudgetLimit: 200,
    targetAgeRanges: ["18-24", "25-34", "35-44"],
    targetGender: "all",
    targetLocations: ["Uganda"],
    targetInterests: ["finance", "mobile", "payments"],
    enableRetargeting: false,
    status: "approved",
  },

  // =========================================================================
  // PLACEMENT: feed — in-feed ads between content items
  // =========================================================================
  {
    id: "ad_003",
    title: "Earn While You Learn — Free Courses",
    headline: "Start Your Tech Career",
    description: "Master Python, JavaScript, and React with our free certified courses. Earn UGX 5,000 per completed module.",
    imageUrl: AD_IMAGES.coding,
    videoUrl: null,
    thumbnailUrl: AD_IMAGES.coding,
    type: "regular",
    placement: "feed",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_002",
    priority: 7,
    frequency: 5,
    targetUrl: "https://example.com/learn-earn",
    callToAction: "learn_more",
    pricingModel: "cpc",
    totalBudget: 8000,
    bidAmount: 0.60,
    dailyBudgetLimit: 300,
    targetAgeRanges: ["18-24", "25-34"],
    targetGender: "all",
    targetLocations: ["Uganda", "Kenya"],
    targetInterests: ["education", "technology", "career"],
    enableRetargeting: true,
    status: "approved",
  },
  {
    id: "ad_004",
    title: "Food Delivery — 50% Off First Order",
    headline: "Hungry? Order Now",
    description: "Fresh meals delivered to your door in 30 minutes. Use code WELCOME50 for 50% off your first order!",
    imageUrl: AD_IMAGES.food,
    videoUrl: null,
    thumbnailUrl: AD_IMAGES.food,
    type: "banner",
    placement: "feed",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_004",
    priority: 8,
    frequency: 5,
    targetUrl: "https://example.com/food-delivery",
    callToAction: "get_offer",
    pricingModel: "cpc",
    totalBudget: 6000,
    bidAmount: 0.75,
    dailyBudgetLimit: 250,
    targetAgeRanges: ["18-24", "25-34", "35-44"],
    targetGender: "all",
    targetLocations: ["Uganda", "Kenya"],
    targetInterests: ["food", "delivery", "restaurants"],
    enableRetargeting: true,
    status: "approved",
  },
  {
    id: "ad_005",
    title: "Crypto Trading Made Easy",
    headline: "Start with UGX 10,000",
    description: "Trade Bitcoin, Ethereum, and 50+ cryptocurrencies. Low fees, secure platform, and instant withdrawals.",
    imageUrl: AD_IMAGES.crypto,
    videoUrl: null,
    thumbnailUrl: AD_IMAGES.crypto,
    type: "featured",
    placement: "feed",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_003",
    priority: 9,
    frequency: 3,
    targetUrl: "https://example.com/crypto-trading",
    callToAction: "sign_up",
    pricingModel: "cpa",
    totalBudget: 15000,
    bidAmount: 3.50,
    dailyBudgetLimit: 600,
    targetAgeRanges: ["18-24", "25-34"],
    targetGender: "all",
    targetLocations: ["Uganda", "Kenya", "Nigeria"],
    targetInterests: ["cryptocurrency", "investing", "trading"],
    enableRetargeting: true,
    status: "approved",
  },

  // =========================================================================
  // PLACEMENT: question — shown in the Questions screen (Q&A feed)
  // =========================================================================
  {
    id: "ad_006",
    title: "Share Knowledge, Earn Rewards",
    headline: "Answer & Earn UGX 500",
    description: "Your expertise is valuable! Answer community questions and earn instant cash rewards. Top contributors earn up to UGX 50,000/week.",
    imageUrl: AD_IMAGES.education,
    videoUrl: null,
    thumbnailUrl: AD_IMAGES.education,
    type: "featured",
    placement: "question",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_002",
    priority: 10,
    frequency: 4,
    targetUrl: "https://example.com/answer-earn",
    callToAction: "learn_more",
    pricingModel: "cpm",
    totalBudget: 8000,
    bidAmount: 2.00,
    dailyBudgetLimit: 350,
    targetAgeRanges: ["18-24", "25-34", "35-44"],
    targetGender: "all",
    targetLocations: ["Uganda", "Kenya", "Tanzania"],
    targetInterests: ["education", "earning", "community"],
    enableRetargeting: false,
    status: "approved",
  },
  {
    id: "ad_007",
    title: "Online Tutoring — Learn Anything",
    headline: "Expert Tutors Available 24/7",
    description: "Get 1-on-1 tutoring from certified experts. Math, Science, English, and more. First session free!",
    imageUrl: AD_IMAGES.laptop,
    videoUrl: null,
    thumbnailUrl: AD_IMAGES.laptop,
    type: "banner",
    placement: "question",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_004",
    priority: 7,
    frequency: 5,
    targetUrl: "https://example.com/online-tutoring",
    callToAction: "sign_up",
    pricingModel: "cpc",
    totalBudget: 5000,
    bidAmount: 0.80,
    dailyBudgetLimit: 200,
    targetAgeRanges: ["13-17", "18-24", "25-34"],
    targetGender: "all",
    targetLocations: ["Uganda", "Kenya"],
    targetInterests: ["education", "learning", "tutoring"],
    enableRetargeting: true,
    status: "approved",
  },
  {
    id: "ad_008",
    title: "Daily Trivia Challenge",
    headline: "Test Your Knowledge",
    description: "Play daily trivia and compete with friends. Win real cash prizes every day. No entry fee required!",
    imageUrl: AD_IMAGES.gaming,
    videoUrl: null,
    thumbnailUrl: AD_IMAGES.gaming,
    type: "regular",
    placement: "question",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_003",
    priority: 6,
    frequency: 6,
    targetUrl: "https://example.com/daily-trivia",
    callToAction: "learn_more",
    pricingModel: "cpm",
    totalBudget: 4000,
    bidAmount: 1.50,
    dailyBudgetLimit: 180,
    targetAgeRanges: ["13-17", "18-24", "25-34"],
    targetGender: "all",
    targetLocations: ["Uganda"],
    targetInterests: ["gaming", "trivia", "earning"],
    enableRetargeting: false,
    status: "approved",
  },

  // =========================================================================
  // PLACEMENT: survey — shown on the Surveys screen
  // =========================================================================
  {
    id: "ad_009",
    title: "Complete Surveys, Earn Cash",
    headline: "UGX 2,000 Per Survey",
    description: "Share your opinions and get paid instantly. Quick 5-minute surveys on topics you care about. Cash out anytime!",
    imageUrl: AD_IMAGES.business,
    videoUrl: null,
    thumbnailUrl: AD_IMAGES.business,
    type: "featured",
    placement: "survey",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_002",
    priority: 9,
    frequency: 4,
    targetUrl: "https://example.com/earn-surveys",
    callToAction: "learn_more",
    pricingModel: "cpm",
    totalBudget: 7000,
    bidAmount: 2.00,
    dailyBudgetLimit: 300,
    targetAgeRanges: ["18-24", "25-34", "35-44"],
    targetGender: "all",
    targetLocations: ["Uganda", "Kenya", "Tanzania"],
    targetInterests: ["surveys", "earning", "opinions"],
    enableRetargeting: false,
    status: "approved",
  },
  {
    id: "ad_010",
    title: "Market Research Panel — Join Free",
    headline: "Your Opinion Matters",
    description: "Join Africa's largest market research panel. Influence products and services while earning rewards. 100% free to join.",
    imageUrl: AD_IMAGES.coffee,
    videoUrl: null,
    thumbnailUrl: AD_IMAGES.coffee,
    type: "banner",
    placement: "survey",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_003",
    priority: 7,
    frequency: 5,
    targetUrl: "https://example.com/research-panel",
    callToAction: "sign_up",
    pricingModel: "cpc",
    totalBudget: 4000,
    bidAmount: 0.65,
    dailyBudgetLimit: 180,
    targetAgeRanges: ["18-24", "25-34", "35-44", "45-54"],
    targetGender: "all",
    targetLocations: ["Uganda", "Kenya"],
    targetInterests: ["surveys", "research", "earning"],
    enableRetargeting: true,
    status: "approved",
  },

  // =========================================================================
  // PLACEMENT: video — shown on the Videos screen
  // =========================================================================
  {
    id: "ad_011",
    title: "Stream Music Premium — 3 Months Free",
    headline: "Ad-Free Music Experience",
    description: "Unlimited music, offline downloads, and ad-free listening. Try 3 months free — cancel anytime!",
    imageUrl: AD_IMAGES.music,
    videoUrl: AD_VIDEOS.forBiggerFun,
    thumbnailUrl: AD_IMAGES.music,
    type: "featured",
    placement: "video",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_004",
    priority: 9,
    frequency: 3,
    targetUrl: "https://example.com/music-premium",
    callToAction: "subscribe",
    pricingModel: "cpa",
    totalBudget: 12000,
    bidAmount: 2.00,
    dailyBudgetLimit: 500,
    targetAgeRanges: ["13-17", "18-24", "25-34"],
    targetGender: "all",
    targetLocations: ["Uganda", "Kenya", "Tanzania", "Nigeria"],
    targetInterests: ["music", "entertainment", "streaming"],
    enableRetargeting: true,
    status: "approved",
  },
  {
    id: "ad_012",
    title: "Fitness App — Transform Your Body",
    headline: "Join 500K+ Active Users",
    description: "Personalized workouts, meal plans, and progress tracking. Start your 7-day free trial today!",
    imageUrl: AD_IMAGES.fitness,
    videoUrl: AD_VIDEOS.forBiggerEscapes,
    thumbnailUrl: AD_IMAGES.fitness,
    type: "banner",
    placement: "video",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_002",
    priority: 7,
    frequency: 4,
    targetUrl: "https://example.com/fitness-app",
    callToAction: "download",
    pricingModel: "cpc",
    totalBudget: 6000,
    bidAmount: 0.55,
    dailyBudgetLimit: 250,
    targetAgeRanges: ["18-24", "25-34", "35-44"],
    targetGender: "all",
    targetLocations: ["Uganda", "Kenya"],
    targetInterests: ["fitness", "health", "wellness"],
    enableRetargeting: true,
    status: "approved",
  },

  // =========================================================================
  // PLACEMENT: profile — shown on user profile screens
  // =========================================================================
  {
    id: "ad_013",
    title: "Upgrade Your Profile — Go Pro",
    headline: "Stand Out From the Crowd",
    description: "Get a verified badge, custom themes, and priority visibility. Pro members earn 2x rewards on every activity!",
    imageUrl: AD_IMAGES.fashion,
    videoUrl: null,
    thumbnailUrl: AD_IMAGES.fashion,
    type: "compact",
    placement: "profile",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_003",
    priority: 6,
    frequency: 3,
    targetUrl: "https://example.com/go-pro",
    callToAction: "sign_up",
    pricingModel: "cpm",
    totalBudget: 3000,
    bidAmount: 1.20,
    dailyBudgetLimit: 150,
    targetAgeRanges: ["18-24", "25-34"],
    targetGender: "all",
    targetLocations: ["Uganda"],
    targetInterests: ["social", "earning", "status"],
    enableRetargeting: false,
    status: "approved",
  },
  {
    id: "ad_014",
    title: "Career Coaching — Free Consultation",
    headline: "Level Up Your Career",
    description: "Connect with expert career coaches. Get a free 30-minute consultation and personalized career roadmap.",
    imageUrl: AD_IMAGES.business,
    videoUrl: null,
    thumbnailUrl: AD_IMAGES.business,
    type: "regular",
    placement: "profile",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_004",
    priority: 5,
    frequency: 4,
    targetUrl: "https://example.com/career-coaching",
    callToAction: "book_now",
    pricingModel: "cpc",
    totalBudget: 4000,
    bidAmount: 0.90,
    dailyBudgetLimit: 180,
    targetAgeRanges: ["18-24", "25-34", "35-44"],
    targetGender: "all",
    targetLocations: ["Uganda", "Kenya"],
    targetInterests: ["career", "business", "growth"],
    enableRetargeting: true,
    status: "approved",
  },

  // =========================================================================
  // PLACEMENT: explore — shown on the Explore/discover screen
  // =========================================================================
  {
    id: "ad_015",
    title: "Travel Uganda — Hidden Gems Await",
    headline: "Explore East Africa",
    description: "Discover breathtaking destinations across Uganda. Book curated tours starting from UGX 50,000. Adventure awaits!",
    imageUrl: AD_IMAGES.travel,
    videoUrl: AD_VIDEOS.forBiggerJoyrides,
    thumbnailUrl: AD_IMAGES.travel,
    type: "featured",
    placement: "explore",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_002",
    priority: 8,
    frequency: 3,
    targetUrl: "https://example.com/travel-uganda",
    callToAction: "book_now",
    pricingModel: "cpm",
    totalBudget: 9000,
    bidAmount: 2.20,
    dailyBudgetLimit: 400,
    targetAgeRanges: ["25-34", "35-44", "45-54"],
    targetGender: "all",
    targetLocations: ["Uganda", "Kenya", "Tanzania"],
    targetInterests: ["travel", "adventure", "tourism"],
    enableRetargeting: true,
    status: "approved",
  },
  {
    id: "ad_016",
    title: "Luxury Hotel Deals — Up to 60% Off",
    headline: "Book Your Dream Stay",
    description: "Exclusive deals on top-rated hotels in Kampala, Nairobi, and Dar es Salaam. Free cancellation on most properties.",
    imageUrl: AD_IMAGES.hotel,
    videoUrl: null,
    thumbnailUrl: AD_IMAGES.hotel,
    type: "banner",
    placement: "explore",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_003",
    priority: 7,
    frequency: 4,
    targetUrl: "https://example.com/hotel-deals",
    callToAction: "book_now",
    pricingModel: "cpc",
    totalBudget: 7000,
    bidAmount: 0.85,
    dailyBudgetLimit: 300,
    targetAgeRanges: ["25-34", "35-44", "45-54"],
    targetGender: "all",
    targetLocations: ["Uganda", "Kenya", "Tanzania"],
    targetInterests: ["travel", "hotels", "luxury"],
    enableRetargeting: true,
    status: "approved",
  },
  {
    id: "ad_017",
    title: "Latest Sneaker Drop — Limited Edition",
    headline: "Shop the Collection",
    description: "Exclusive sneakers from top brands. Limited stock available. Free delivery on orders over UGX 100,000.",
    imageUrl: AD_IMAGES.sneakers,
    videoUrl: null,
    thumbnailUrl: AD_IMAGES.sneakers,
    type: "regular",
    placement: "explore",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_004",
    priority: 6,
    frequency: 5,
    targetUrl: "https://example.com/sneaker-drop",
    callToAction: "shop_now",
    pricingModel: "cpc",
    totalBudget: 5000,
    bidAmount: 0.70,
    dailyBudgetLimit: 220,
    targetAgeRanges: ["13-17", "18-24", "25-34"],
    targetGender: "all",
    targetLocations: ["Uganda", "Kenya"],
    targetInterests: ["fashion", "sneakers", "streetwear"],
    enableRetargeting: true,
    status: "approved",
  },

  // =========================================================================
  // EXTRA: Additional feed/question ads for variety in scrolling
  // =========================================================================
  {
    id: "ad_018",
    title: "Wellness & Yoga — First Class Free",
    headline: "Find Your Inner Peace",
    description: "Join online yoga and meditation classes. Certified instructors, flexible schedule. Your first class is on us!",
    imageUrl: AD_IMAGES.yoga,
    videoUrl: null,
    thumbnailUrl: AD_IMAGES.yoga,
    type: "compact",
    placement: "feed",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_004",
    priority: 5,
    frequency: 4,
    targetUrl: "https://example.com/yoga-class",
    callToAction: "sign_up",
    pricingModel: "cpc",
    totalBudget: 3000,
    bidAmount: 0.50,
    dailyBudgetLimit: 150,
    targetAgeRanges: ["18-24", "25-34", "35-44"],
    targetGender: "all",
    targetLocations: ["Uganda"],
    targetInterests: ["wellness", "yoga", "meditation"],
    enableRetargeting: false,
    status: "approved",
  },
  {
    id: "ad_019",
    title: "Smart Home Devices — 40% Off Today",
    headline: "Upgrade Your Home",
    description: "Transform your home with smart speakers, lights, and security cameras. Save 40% this week only!",
    imageUrl: AD_IMAGES.home,
    videoUrl: null,
    thumbnailUrl: AD_IMAGES.home,
    type: "regular",
    placement: "question",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_002",
    priority: 5,
    frequency: 5,
    targetUrl: "https://example.com/smart-home",
    callToAction: "shop_now",
    pricingModel: "cpm",
    totalBudget: 4000,
    bidAmount: 1.50,
    dailyBudgetLimit: 200,
    targetAgeRanges: ["25-34", "35-44", "45-54"],
    targetGender: "all",
    targetLocations: ["Uganda", "Kenya"],
    targetInterests: ["technology", "home", "gadgets"],
    enableRetargeting: true,
    status: "approved",
  },
  {
    id: "ad_020",
    title: "New Car Deals — Drive Your Dream",
    headline: "0% Finance Available",
    description: "Explore the latest models with 0% financing for 12 months. Trade-in your old car and save extra. Visit a showroom today!",
    imageUrl: AD_IMAGES.car,
    videoUrl: null,
    thumbnailUrl: AD_IMAGES.car,
    type: "featured",
    placement: "question",
    sponsored: true,
    isActive: true,
    startDate: "2026-01-01T00:00:00Z",
    endDate: "2027-12-31T23:59:59Z",
    userId: "user_003",
    priority: 8,
    frequency: 3,
    targetUrl: "https://example.com/car-deals",
    callToAction: "learn_more",
    pricingModel: "cpm",
    totalBudget: 12000,
    bidAmount: 2.80,
    dailyBudgetLimit: 500,
    targetAgeRanges: ["25-34", "35-44", "45-54"],
    targetGender: "all",
    targetLocations: ["Uganda", "Kenya"],
    targetInterests: ["automotive", "cars", "finance"],
    enableRetargeting: true,
    status: "approved",
  },
];

// ===========================================
// Mock Questions
// ===========================================
export const mockQuestions = [
  {
    id: "question_001",
    text: "What is your favorite programming language and why?",
    userId: "user_002",
    createdAt: "2026-01-03T10:00:00Z",
    updatedAt: "2026-01-03T10:00:00Z",
    category: "Technology",
    rewardAmount: 5.0,
    isInstantReward: true,
    totalAnswers: 234,
  },
  {
    id: "question_002",
    text: "How do you stay productive while working remotely?",
    userId: "user_003",
    createdAt: "2026-01-03T11:30:00Z",
    updatedAt: "2026-01-03T11:30:00Z",
    category: "Lifestyle",
    rewardAmount: 3.5,
    isInstantReward: true,
    totalAnswers: 156,
  },
  {
    id: "question_003",
    text: "What are the best practices for mobile app development?",
    userId: "user_004",
    createdAt: "2026-01-03T14:20:00Z",
    updatedAt: "2026-01-03T14:20:00Z",
    category: "Technology",
    rewardAmount: 7.5,
    isInstantReward: false,
    totalAnswers: 89,
  },
  {
    id: "question_004",
    text: "How do you manage your personal finances?",
    userId: "user_002",
    createdAt: "2026-01-02T09:00:00Z",
    updatedAt: "2026-01-02T09:00:00Z",
    category: "Finance",
    rewardAmount: 10.0,
    isInstantReward: true,
    totalAnswers: 312,
  },
  {
    id: "question_005",
    text: "What motivates you to work every day?",
    userId: "user_003",
    createdAt: "2026-01-01T15:00:00Z",
    updatedAt: "2026-01-01T15:00:00Z",
    category: "Lifestyle",
    rewardAmount: 7.5,
    isInstantReward: false,
    totalAnswers: 178,
  },
];

// ===========================================
// Mock Responses (Answers to Questions)
// ===========================================
export const mockResponses = [
  {
    id: "response_001",
    responseText: "TypeScript is my favorite because of its strong typing system and excellent IDE support. It catches errors at compile time and makes refactoring much safer.",
    userId: "user_001",
    questionId: "question_001",
    createdAt: "2026-01-03T10:15:00Z",
    updatedAt: "2026-01-03T10:15:00Z",
    likesCount: 45,
    dislikesCount: 2,
    repliesCount: 5,
    isLiked: false,
    isDisliked: false,
  },
  {
    id: "response_002",
    responseText: "Python for its simplicity and vast ecosystem of libraries. It's perfect for data science and machine learning projects.",
    userId: "user_004",
    questionId: "question_001",
    createdAt: "2026-01-03T10:30:00Z",
    updatedAt: "2026-01-03T10:30:00Z",
    likesCount: 78,
    dislikesCount: 5,
    repliesCount: 8,
    isLiked: true,
    isDisliked: false,
  },
  {
    id: "response_003",
    responseText: "I use the Pomodoro technique and have a dedicated workspace. Also, regular breaks and a strict schedule help maintain focus.",
    userId: "user_002",
    questionId: "question_002",
    createdAt: "2026-01-03T12:00:00Z",
    updatedAt: "2026-01-03T12:00:00Z",
    likesCount: 32,
    dislikesCount: 1,
    repliesCount: 3,
    isLiked: false,
    isDisliked: false,
  },
];

// ===========================================
// Mock Response Replies
// ===========================================
export const mockResponseReplies = [
  {
    id: "reply_001",
    replyText: "I agree! TypeScript has been a game changer for our team.",
    userId: "user_003",
    responseId: "response_001",
    createdAt: "2026-01-03T10:45:00Z",
    updatedAt: "2026-01-03T10:45:00Z",
  },
  {
    id: "reply_002",
    replyText: "Have you tried using VS Code with TypeScript? The integration is amazing!",
    userId: "user_004",
    responseId: "response_001",
    createdAt: "2026-01-03T11:00:00Z",
    updatedAt: "2026-01-03T11:00:00Z",
  },
];

// ===========================================
// Mock Reward Questions
// ===========================================
export const mockRewardQuestions = [
  {
    id: "rq_001",
    text: "What is the capital of France?",
    options: { a: "London", b: "Berlin", c: "Paris", d: "Madrid" },
    correctAnswer: "c",
    rewardAmount: 5000,
    expiryTime: getFutureDate(14),
    isActive: true,
    userId: "user_002",
    createdAt: getTodayDate(),
    updatedAt: getTodayDate(),
    isInstantReward: true,
    maxWinners: 3,
    winnersCount: 3,
    isCompleted: false,
    paymentProvider: "MTN",
    phoneNumber: "+256 700 123 456",
  },
  {
    id: "rq_002",
    text: "Which planet is known as the Red Planet?",
    options: { a: "Venus", b: "Mars", c: "Jupiter", d: "Saturn" },
    correctAnswer: "b",
    rewardAmount: 10000,
    expiryTime: getFutureDate(14),
    isActive: true,
    userId: "user_003",
    createdAt: getTodayDate(),
    updatedAt: getTodayDate(),
    isInstantReward: true,
    maxWinners: 3,
    winnersCount: 3,
    isCompleted: false,
    paymentProvider: "AIRTEL",
    phoneNumber: "+256 700 234 567",
  },
  {
    id: "rq_003",
    text: "What is the largest ocean on Earth?",
    options: { a: "Atlantic Ocean", b: "Indian Ocean", c: "Pacific Ocean", d: "Arctic Ocean" },
    correctAnswer: "c",
    rewardAmount: 7500,
    expiryTime: getFutureDate(14),
    isActive: true,
    userId: "user_001",
    createdAt: getTodayDate(),
    updatedAt: getTodayDate(),
    isInstantReward: true,
    maxWinners: 2,
    winnersCount: 2,
    isCompleted: false,
    paymentProvider: "MTN",
    phoneNumber: "+256 700 345 678",
  },
  {
    id: "rq_004",
    text: "Who painted the Mona Lisa?",
    options: { a: "Vincent van Gogh", b: "Pablo Picasso", c: "Leonardo da Vinci", d: "Michelangelo" },
    correctAnswer: "c",
    rewardAmount: 15000,
    expiryTime: getFutureDate(14),
    isActive: true,
    userId: "user_002",
    createdAt: getTodayDate(),
    updatedAt: getTodayDate(),
    isInstantReward: true,
    maxWinners: 1,
    winnersCount: 1,
    isCompleted: false,
    paymentProvider: "AIRTEL",
    phoneNumber: "+256 700 456 789",
  },
  {
    id: "rq_005",
    text: "What is the chemical symbol for Gold?",
    options: { a: "Go", b: "Gd", c: "Au", d: "Ag" },
    correctAnswer: "c",
    rewardAmount: 8000,
    expiryTime: getFutureDate(14),
    isActive: true,
    userId: "user_003",
    createdAt: getTodayDate(),
    updatedAt: getTodayDate(),
    isInstantReward: true,
    maxWinners: 3,
    winnersCount: 3,
    isCompleted: false,
    paymentProvider: "MTN",
    phoneNumber: "+256 700 567 890",
  },
  {
    id: "rq_006",
    text: "In which year did World War II end?",
    options: { a: "1943", b: "1944", c: "1945", d: "1946" },
    correctAnswer: "c",
    rewardAmount: 12000,
    expiryTime: getFutureDate(14),
    isActive: true,
    userId: "user_001",
    createdAt: getTodayDate(),
    updatedAt: getTodayDate(),
    isInstantReward: true,
    maxWinners: 2,
    winnersCount: 0,
    isCompleted: false,
    paymentProvider: "AIRTEL",
    phoneNumber: "+256 700 678 901",
  },
  {
    id: "rq_007",
    text: "What is the smallest country in the world?",
    options: { a: "Monaco", b: "San Marino", c: "Vatican City", d: "Liechtenstein" },
    correctAnswer: "c",
    rewardAmount: 6000,
    expiryTime: getFutureDate(14),
    isActive: true,
    userId: "user_002",
    createdAt: getTodayDate(),
    updatedAt: getTodayDate(),
    isInstantReward: true,
    maxWinners: 3,
    winnersCount: 3,
    isCompleted: false,
    paymentProvider: "MTN",
    phoneNumber: "+256 700 789 012",
  },
  {
    id: "rq_008",
    text: "Which programming language was created by Guido van Rossum?",
    options: { a: "Java", b: "C++", c: "Python", d: "Ruby" },
    correctAnswer: "c",
    rewardAmount: 20000,
    expiryTime: getFutureDate(14),
    isActive: true,
    userId: "user_003",
    createdAt: getTodayDate(),
    updatedAt: getTodayDate(),
    isInstantReward: true,
    maxWinners: 3,
    winnersCount: 0,
    isCompleted: false,
    paymentProvider: "AIRTEL",
    phoneNumber: "+256 700 890 123",
  },
  // Regular reward questions (non-instant) for Answer Questions & Earn!
  {
    id: "rq_009",
    text: "What is the local currency of Uganda?",
    options: { a: "Kenyan Shilling", b: "Ugandan Shilling", c: "Naira", d: "Rupee" },
    correctAnswer: "b",
    rewardAmount: 5000,
    expiryTime: getFutureDate(14),
    isActive: true,
    userId: "user_002",
    createdAt: getTodayDate(),
    updatedAt: getTodayDate(),
    isInstantReward: false,
    maxWinners: 500,
    winnersCount: 0,
    isCompleted: false,
    paymentProvider: "MTN",
    phoneNumber: "+256 700 123 456",
  },
  {
    id: "rq_010",
    text: "Which mobile money provider launched first in Uganda?",
    options: { a: "Airtel Money", b: "MTN Mobile Money", c: "M-Pesa", d: "Wave" },
    correctAnswer: "b",
    rewardAmount: 8000,
    expiryTime: getFutureDate(14),
    isActive: true,
    userId: "user_001",
    createdAt: getTodayDate(),
    updatedAt: getTodayDate(),
    isInstantReward: false,
    maxWinners: 300,
    winnersCount: 0,
    isCompleted: false,
    paymentProvider: "AIRTEL",
    phoneNumber: "+256 700 345 678",
  },
  // Completed example for history/analytics
  {
    id: "rq_011",
    text: "How many colors are on the Ugandan flag?",
    options: { a: "2", b: "3", c: "5", d: "6" },
    correctAnswer: "c",
    rewardAmount: 4000,
    expiryTime: getTodayDate(),
    isActive: false,
    userId: "user_004",
    createdAt: "2025-12-20T00:00:00Z",
    updatedAt: "2026-01-05T00:00:00Z",
    isInstantReward: false,
    maxWinners: 200,
    winnersCount: 200,
    isCompleted: true,
    paymentProvider: "MTN",
    phoneNumber: "+256 700 456 789",
  },
];

// ===========================================
// Mock Quiz Questions
// ===========================================
export const mockQuizQuestions = [
  {
    id: "quiz_001",
    text: "What is the largest planet in our solar system?",
    options: { a: "Earth", b: "Mars", c: "Jupiter", d: "Saturn" },
    correctAnswer: "c",
    explanation: "Jupiter is the largest planet in our solar system, with a mass more than twice that of all the other planets combined.",
    category: "Science",
    difficulty: "easy",
    pointValue: 10,
    timeLimit: 90,
    type: "single_choice",
  },
  {
    id: "quiz_002",
    text: "Which programming language is known as the 'language of the web'?",
    options: { a: "Python", b: "JavaScript", c: "Java", d: "C++" },
    correctAnswer: "b",
    explanation: "JavaScript is the primary programming language for web development, running in browsers and on servers via Node.js.",
    category: "Technology",
    difficulty: "easy",
    pointValue: 10,
    timeLimit: 90,
    type: "single_choice",
  },
  {
    id: "quiz_003",
    text: "What year did the first iPhone launch?",
    options: { a: "2005", b: "2006", c: "2007", d: "2008" },
    correctAnswer: "c",
    explanation: "The first iPhone was unveiled by Steve Jobs on January 9, 2007, and released on June 29, 2007.",
    category: "Technology",
    difficulty: "medium",
    pointValue: 15,
    timeLimit: 90,
    type: "single_choice",
  },
  {
    id: "quiz_004",
    text: "Which country has the largest population in Africa?",
    options: { a: "Ethiopia", b: "Egypt", c: "South Africa", d: "Nigeria" },
    correctAnswer: "d",
    explanation: "Nigeria has the largest population in Africa with over 200 million people.",
    category: "Geography",
    difficulty: "medium",
    pointValue: 15,
    timeLimit: 90,
    type: "single_choice",
  },
  {
    id: "quiz_005",
    text: "What is the chemical symbol for Gold?",
    options: { a: "Go", b: "Gd", c: "Au", d: "Ag" },
    correctAnswer: "c",
    explanation: "The chemical symbol for Gold is Au, derived from the Latin word 'aurum'.",
    category: "Science",
    difficulty: "easy",
    pointValue: 10,
    timeLimit: 90,
    type: "single_choice",
  },
  {
    id: "quiz_006",
    text: "Which company owns Instagram?",
    options: { a: "Google", b: "Microsoft", c: "Meta (Facebook)", d: "Twitter" },
    correctAnswer: "c",
    explanation: "Instagram was acquired by Facebook (now Meta) in 2012 for approximately $1 billion.",
    category: "Technology",
    difficulty: "easy",
    pointValue: 10,
    timeLimit: 90,
    type: "single_choice",
  },
  {
    id: "quiz_007",
    text: "What is the capital city of Uganda?",
    options: { a: "Nairobi", b: "Kampala", c: "Dar es Salaam", d: "Kigali" },
    correctAnswer: "b",
    explanation: "Kampala is the capital and largest city of Uganda, located on the shores of Lake Victoria.",
    category: "Geography",
    difficulty: "easy",
    pointValue: 10,
    timeLimit: 90,
    type: "single_choice",
  },
  {
    id: "quiz_008",
    text: "How many continents are there on Earth?",
    options: { a: "5", b: "6", c: "7", d: "8" },
    correctAnswer: "c",
    explanation: "There are 7 continents: Africa, Antarctica, Asia, Australia, Europe, North America, and South America.",
    category: "Geography",
    difficulty: "easy",
    pointValue: 10,
    timeLimit: 90,
    type: "single_choice",
  },
  {
    id: "quiz_009",
    text: "What does 'HTTP' stand for?",
    options: { a: "HyperText Transfer Protocol", b: "High Tech Transfer Protocol", c: "Hyper Terminal Transfer Program", d: "Home Tool Transfer Protocol" },
    correctAnswer: "a",
    explanation: "HTTP stands for HyperText Transfer Protocol, the foundation of data communication on the World Wide Web.",
    category: "Technology",
    difficulty: "medium",
    pointValue: 15,
    timeLimit: 90,
    type: "single_choice",
  },
  {
    id: "quiz_010",
    text: "Which planet is known as the 'Red Planet'?",
    options: { a: "Venus", b: "Mars", c: "Jupiter", d: "Mercury" },
    correctAnswer: "b",
    explanation: "Mars is called the Red Planet because of its reddish appearance, caused by iron oxide (rust) on its surface.",
    category: "Science",
    difficulty: "easy",
    pointValue: 10,
    timeLimit: 90,
    type: "single_choice",
  },
  {
    id: "quiz_011",
    text: "Python is a compiled programming language.",
    options: ["True", "False"],
    correctAnswer: "False",
    explanation: "Python is an interpreted language, not a compiled one. It executes code line by line at runtime.",
    category: "Technology",
    difficulty: "medium",
    pointValue: 15,
    timeLimit: 60,
    type: "boolean",
  },
  {
    id: "quiz_012",
    text: "The Great Wall of China is visible from space with the naked eye.",
    options: ["True", "False"],
    correctAnswer: "False",
    explanation: "This is a common myth. The Great Wall is not visible from space with the naked eye due to its relatively narrow width.",
    category: "General Knowledge",
    difficulty: "medium",
    pointValue: 15,
    timeLimit: 60,
    type: "boolean",
  },
];
